### ISSUE TITLE
The plugin is not working with CORS

### ISSUE THREAD

**Issue by JakubJagoda** [p-meier/hapi-api-version#1]
Hi! First of all, thanks for sharing this useful plugin. It's exactly what I needed, however I noticed that it doesn't work with CORS, namely with preflight OPTION request that browser is sending to the server before cross-origin request. Consider this simple setup:

```js
const Hapi = require('hapi');
const server = new Hapi.Server();

server.connection({
    port: process.env.PORT || 5000,
    routes: {
        cors: {
            origin: ['*']
        }
    }
});

server.register({
    register: require('hapi-api-version'),
    options: {
        validVersions: [1, 2],
        defaultVersion: 1,
        vendorName: 'api'
    }
}, () => {
    server.route({
        path: '/',
        method: 'GET',
        config: {
            handler(request, reply) {
                reply('Hello world!');
            }
        }
    });

    server.start(function () {
        console.log('*** Server running at:', server.info.uri);
    });
});
```
It's worth to note that I'm using hapi 12.1.0 here, but I also tested with 11 and results were the same. So, let's send a cross-origin request to it:
`curl "http://localhost:5000" -X OPTIONS -H "Access-Control-Request-Method: GET" -H "Origin: http://localhost:8000" -H "Accept: */*" -H "Access-Control-Request-Headers: accept, authorization" -H "Referer: http://localhost:8000"`
The result:
`{"statusCode":404,"error":"Not Found"}`
If we change the code so that it does not use the plugin anymore, then out simulated preflight request succeeds. In Chrome devtools we can see the message:
>XMLHttpRequest cannot load http://localhost:5000. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 404.

And indeed, the response doesn't contain such a header.

Hope this will get covered, I would be happy to track the issue and send a pull request, but I'm not sure when I have enough time for that.

**Comment by p-meier** [comment]
I will look into that as soon as I have time.

**Comment by JakubJagoda** [comment]
Cool. I did some tracking yesterday and it seems that inside the `onPreResponse` server extension:
```js
server.ext('onPreResponse', (request, reply) => {
        //breakpoint here
    });
```
 the `request.response` is already an `Error` instance with message `"Not found"` and status code 404. So it either means there was some problems with route matching or I did something wrong in the setup or something else happens and hapi internals are written in such a way that this results in 404 code.

**Comment by ejeklint** [comment]
This should be fixed with my PR that just have been integrated. CORS makes a catch-all route magically show up. See https://github.com/p-meier/hapi-api-version/pull/2 

I just tested with that patch and your code runs fine.

**Comment by p-meier** [comment]
That's right. The PR from @ejeklint actually Closes this issue as well. Thanks a lot for that.

**Comment by JakubJagoda** [comment]
@p-meier thank you, and thank you @ejeklint for the solution

**Comment by p-meier** [comment]
Just published a new version of the package. So you can upgrade to '1.0.1' and use it again.
