### ISSUE TITLE
Custom basePath early exit

### ISSUE THREAD

**Issue by adam-26** [p-meier/hapi-api-version#10]
Hi, if using a custom basePath (not '/'), when determining if the request should be re-written to use a versioned route the plugin should exit early if the requested path does not start with the custom basePath. Would you accept a PR with this implemented?

Thanks, Adam.

**Comment by p-meier** [comment]
Sry. I don't understand the question you are asking. What do you mean with _exit early_? Could you please give a more detailed explanation?
