### ISSUE TITLE
Plugin can not handle multiple server connections.

### ISSUE THREAD

**Issue by Uptown76** [p-meier/hapi-api-version#13]
The following error is produced:

Uncaught error: Method not available when the selection has more than one connection or none

on hapi-api-version/index.js:89:30.

The `server.match` method seems to only work when there is a single server connection.

https://hapijs.com/api#servermatchmethod-path-host

**Comment by p-meier** [comment]
You are right. Currently it only supports one connection. Problem is I actually have no time to fix the issue - maybe you can create a pull request for it.
