### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by j0h** [p-meier/hapi-api-version#32]
Would you please be able to update the dependencies (boom, hoek, joi) as they are currently throwing warnings on install, thanks.

**Comment by timcosta** [comment]
Hey! This is on my list of things to do, but as they are just deprecation warnings, it's pretty low on my list :) Happy to accept a PR, there is one that is half done right now but the person who opened it hasn't responded to my comments. I'll try to get to this in the next week or two otherwise.

**Comment by timcosta** [comment]
2.3.0 published!

**Comment by j0h** [comment]
Awesome, thanks @timcosta, much appreciated.
