### ISSUE TITLE
Assigned pre.apiVersion only when versioned route used

### ISSUE THREAD

**Issue by adam-26** [p-meier/hapi-api-version#9]
Hi, if you look at https://github.com/p-meier/hapi-api-version/blob/master/index.js#L96, the apiVersion is assigned the the request.pre prop even if no versioned route was found. This makes it impossible to tell from within the route handler if the request was made directly to the versioned route, or if the request has been re-written by the plugin to use the versioned route. Would you accept a pull-request where the apiVersion is only assigned to the `request.pre` prop when the request url is re-written to use a versioned route? (move the apiVersion assignment to line 93)

Thanks, Adam.

**Comment by p-meier** [comment]
As with your other request the answer is sadly a no. I explain why I wouldn't accept a pull request doing this...

The idea behind the default version is that you want the client to use the newest (or some specific) version of your api if not provided some version header. Also I don't want to force the client providing a version header, thus the default version.

On the handler side you are right - there is no way to determine if the client actually provided a version or if just the default version was used. Can you briefly describe the case which makes you think you need to have this information in the handler?

**Comment by adam-26** [comment]
Hi @p-meier,  
Depending on how the version was defined may impact authentication, or the (meta) data that needs to be returned as part of the request. 

I have created a fork and applied the changes I require. The fork allows you to register the plugin multiple times, and if the request is made with an invalid version number the fork returns an error (I think this is a better approach. If for example, you request version 1, but that version is no longer being serviced, I would prefer to receive an explicit error than have for example version 3 attempt to process the request, and return validation errors). 

FYI, according to the hapi docs use of `request.pre` is for route prerequisite functions, instead you should probably be assigning plugin data to `request.plugins['hapi-api-version']`.

Thanks for the plugin, forking your work saved me some time :)

**Comment by p-meier** [comment]
Hi Adam,

I think this is the best way to do your own fork and work with that. 

As for invalid version - if you look to the source code closely you will find that this already happens. If you provide an invalid version you get an error instead of using default version or something else.

As for the `request.pre` you may be rigtht. Thanks for the hint.

**Comment by adam-26** [comment]
Hi @p-meier, just to clarify what I said about not failing for invalid versions. Your code will fail if a valid version can be extracted, but if you pass a version of 'abc' for example, the plugin will assign that request the default version. This is because in both your 'extractVersion' methods you return null if the header can not be parsed, no error is returned.
